// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxcxiyyddyknprcdgxsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4Y3hpeXlkZHlrbnByY2RneHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjg1NjEsImV4cCI6MjA2Mzc0NDU2MX0.bKWGSVwWG8k17kx8PEvGJTE-zK1NrWrPpoIKHQqMI5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);